### ISSUE TITLE
[CUDA] std::bad_alloc on system with multiple GPUs

### ISSUE THREAD

**Issue by tdavidcl** [AdaptiveCpp/AdaptiveCpp#1258]
**Bug summary**

On a DGX system with 4 A100 :
Launching a basic SYCL kernel on the second GPU (order given by `.get_devices();`) create a crash with 
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

**To Reproduce**
All system with multiple Nvidia GPUs ?

**acpp debug level 3**

After init : 
```
[AdaptiveCpp Info] data_region: constructed with page table dimensions 1 1 1
[AdaptiveCpp Info] data_region: constructed with page table dimensions 1 1 1
[AdaptiveCpp Info] accessor [host]: Initializing host access
[AdaptiveCpp Info] accessor [host]: forcing DAG flush for host access...
[AdaptiveCpp Info] dag_manager: Submitting asynchronous flush...
[AdaptiveCpp Info] dag_builder: DAG contains operations: 
[AdaptiveCpp Info] 0. MEM_REQ: Discard W host_buffer {0, 0, 0}+{1, 1, 100000} #1 @node 0x55a9b70f6270
[AdaptiveCpp Info] dag_manager: waiting for async worker...
[AdaptiveCpp Info] dag_manager [async]: Flushing!
[AdaptiveCpp Info] dag_manager [async]: Submitting node to scheduler!
[AdaptiveCpp Info] [AdaptiveCpp Info] data_region::~data_region: Freeing allocation dag_direct_scheduler: Setting device data pointer of requirement node 0x55a9b08c31e0
MEM_REQ: Discard W host_buffer {0, 0, 0}+{1, 1, 100000} #1 to 0x55a9b7310110
[AdaptiveCpp Info] dag_manager [async]: DAG flush complete.
[AdaptiveCpp Info] data_region::~data_region: Freeing allocation 0x7f4075c00200
[AdaptiveCpp Info] dag_manager: Checking DAG flush opportunity...
[AdaptiveCpp Info] accessor [host]: Waiting for completion of host access...
[AdaptiveCpp Info] cuda_device_manager: Switchting to device 1
[AdaptiveCpp Info] accessor [host]: Initializing host access
[AdaptiveCpp Info] accessor [host]: forcing DAG flush for host access...
[AdaptiveCpp Info] dag_manager: Submitting asynchronous flush...
[AdaptiveCpp Info] dag_builder: DAG contains operations: 
[AdaptiveCpp Info] 0. MEM_REQ: R host_buffer {0, 0, 0}+{1, 1, 100000} #1 @node 0x55a9b7299460
[AdaptiveCpp Info] dag_manager: waiting for async worker...
[AdaptiveCpp Info] dag_manager [async]: Flushing!
[AdaptiveCpp Info] dag_manager [async]: Submitting node to scheduler!
[AdaptiveCpp Info] dag_direct_scheduler: Setting device data pointer of requirement node MEM_REQ: R host_buffer {0, 0, 0}+{1, 1, 100000} #1 to 0x55a9b7310110
[AdaptiveCpp Info] dag_manager [async]: DAG flush complete.
[AdaptiveCpp Info] dag_manager: Checking DAG flush opportunity...
[AdaptiveCpp Info] accessor [host]: Waiting for completion of host access...
[AdaptiveCpp Info] dag_manager: Checking DAG flush opportunity...
[AdaptiveCpp Info] dag_manager: Submitting asynchronous flush...
[AdaptiveCpp Info] dag_builder: DAG contains operations: 
[AdaptiveCpp Info] 0. Memcpy: CPU-Device0 #1 {0, 0, 0}+{1, 1, 100000}-->CPU-Device0 #1 {0, 0, 0}+{1, 1, 100000}{1, 1, 100000} @node 0x55a9b7011aa0
[AdaptiveCpp Info] dag_manager: waiting for async worker...
[AdaptiveCpp Info] dag_manager [async]: Flushing!
[AdaptiveCpp Info] dag_manager [async]: Submitting node to scheduler!
[AdaptiveCpp Info] multi_queue_executor: Processing node 0x55a9b7011aa0 with 0 non-virtual requirement(s) and 0 direct requirement(s).
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

**syclcc hipsycl version**

```
$ syclcc --hipsycl-version
acpp [AdaptiveCpp compilation driver], Copyright (C) 2018-2023 Aksel Alpay and the AdaptiveCpp project
  AdaptiveCpp version: 23.10.0+git.1fd4f9fb.20231114.branch.HEAD
  Installation root: /<obsucate path>/sycl_compilers/acpp
  Plugin LLVM version: 14, can accelerate CPU: True
  Available runtime backends:
     librt-backend-cuda.so
     librt-backend-ocl.so
     librt-backend-omp.so


Full configuration [can be overriden using environment variables or command line arguments]:
    version-major: 23
    version-minor: 10
    version-patch: 0
    version-suffix: +git.1fd4f9fb.20231114.branch.HEAD
    plugin-llvm-version-major: 14
    plugin-with-cpu-acceleration: true
    default-clang: /usr/lib/llvm-14/bin/clang++
    default-nvcxx: (unconfigured)
    default-platform: cuda
    default-cuda-path: /local/tdavidcl/opt/cuda
    default-gpu-arch: (unconfigured)
    default-cpu-cxx: /usr/bin/c++
    default-rocm-path: /opt/rocm
    default-use-bootstrap-mode: false
    default-is-dryrun: false
    default-use-accelerated-cpu: true
    default-clang-include-path: /usr/lib/llvm-14/lib/clang/14.0.6/include/..
    default-sequential-link-line: -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu
    default-sequential-cxx-flags: -I/usr/include -D_ENABLE_EXTENDED_ALIGNED_STORAGE
    default-omp-link-line: -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu -fopenmp
    default-omp-cxx-flags: -I/usr/include -fopenmp -D_ENABLE_EXTENDED_ALIGNED_STORAGE
    default-rocm-link-line: -Wl,-rpath=$HIPSYCL_ROCM_PATH/lib -Wl,-rpath=$HIPSYCL_ROCM_PATH/hip/lib -L/opt/rocm/lib -L/opt/rocm/hip/lib -lamdhip64
    default-rocm-cxx-flags: -isystem $HIPSYCL_PATH/include/AdaptiveCpp/hipSYCL/std/hiplike -isystem /usr/lib/llvm-14/lib/clang/14.0.6/include/.. -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -I$HIPSYCL_ROCM_PATH/include -I$HIPSYCL_ROCM_PATH/include --rocm-device-lib-path=$HIPSYCL_ROCM_PATH/amdgcn/bitcode --rocm-path=$HIPSYCL_ROCM_PATH -fhip-new-launch-api -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -D__HIP_ROCclr__
    default-cuda-link-line: -Wl,-rpath=$HIPSYCL_CUDA_LIB_PATH -L$HIPSYCL_CUDA_LIB_PATH -lcudart
    default-cuda-cxx-flags: -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -isystem $HIPSYCL_PATH/include/AdaptiveCpp/hipSYCL/std/hiplike
    default-is-explicit-multipass: false
    default-save-temps: false
```

**gdb backtrace**
```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007fffbda8fd9f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007fffbda40f32 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007fffbda2b472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007fffbdc83919 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fffbdc8ee1a in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fffbdc8ee85 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fffbdc8f0d8 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fffbdc83524 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007fffbe1fef5a in std::vector<int, sbo::small_buffer_vector_allocator<int, 8ul, int> >::_M_default_append(unsigned long) ()
   from /<obsucate path>/sycl_compilers/acpp//lib/libacpp-rt.so
#10 0x00007fffbe1fc9ae in hipsycl::rt::(anonymous namespace)::determine_target_lane(std::shared_ptr<hipsycl::rt::dag_node>, sbo::small_vector<std::shared_ptr<hipsycl::rt::dag_node>, 8ul> const&, hipsycl::rt::multi_queue_executor const*, hipsycl::rt::moving_statistics const&, hipsycl::rt::backend_execution_lane_range) () from /<obsucate path>/sycl_compilers/acpp//lib/libacpp-rt.so
#11 0x00007fffbe1fda63 in hipsycl::rt::multi_queue_executor::submit_directly(std::shared_ptr<hipsycl::rt::dag_node>, hipsycl::rt::operation*, sbo::small_vector<std::shared_ptr<hipsycl::rt::dag_node>, 8ul> const&) () from /<obsucate path>/sycl_compilers/acpp//lib/libacpp-rt.so
#12 0x00007fffbe209122 in hipsycl::rt::(anonymous namespace)::submit(hipsycl::rt::backend_executor*, std::shared_ptr<hipsycl::rt::dag_node>, hipsycl::rt::operation*) ()
   from /<obsucate path>/sycl_compilers/acpp//lib/libacpp-rt.so
#13 0x00007fffbe20f642 in hipsycl::rt::dag_direct_scheduler::submit(std::shared_ptr<hipsycl::rt::dag_node>) () from /<obsucate path>/sycl_compilers/acpp//lib/libacpp-rt.so
#14 0x00007fffbe210809 in hipsycl::rt::dag_unbound_scheduler::submit(std::shared_ptr<hipsycl::rt::dag_node>) () from /<obsucate path>/sycl_compilers/acpp//lib/libacpp-rt.so
#15 0x00007fffbe21219a in std::_Function_handler<void (), hipsycl::rt::dag_manager::flush_async()::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from /<obsucate path>/sycl_compilers/acpp//lib/libacpp-rt.so
#16 0x00007fffbe21a2ab in hipsycl::rt::worker_thread::work() () from /<obsucate path>/sycl_compilers/acpp//lib/libacpp-rt.so
#17 0x00007fffbdcba4a3 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#18 0x00007fffbda8e044 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#19 0x00007fffbdb0e61c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**acpp-info**

```
acpp-info 
[AdaptiveCpp Warning] ocl_hardware_manager: OpenCL device 'pthread-haswell-AMD EPYC 7742 64-Core Processor' does not support SPIR-V; hiding device. Set ACPP_RT_OCL_SHOW_ALL_DEVICES=1 to override.
[AdaptiveCpp Warning] ocl_hardware_manager: Platform 'Intel(R) OpenCL' does not support OpenCL 3.0; hiding platform. Set ACPP_RT_OCL_SHOW_ALL_DEVICES=1 to override. (OpenCL version string was: 'OpenCL 1.2 LINUX')
[AdaptiveCpp Warning] from /<obsucate path>/sycl_compiler_gits/AdaptiveCpp/src/runtime/ocl/ocl_hardware_manager.cpp:599 @ ocl_hardware_manager(): ocl_hardware_manager: Shared context construction failed. Will attempt to fall back to individual context per device, but this may prevent data transfers between devices from working. (error code = CL:-30)
=================Backend information===================
Loaded backend 0: CUDA
  Found device: NVIDIA A100-SXM4-40GB
  Found device: NVIDIA A100-SXM4-40GB
  Found device: NVIDIA A100-SXM4-40GB
  Found device: NVIDIA A100-SXM4-40GB
  Found device: NVIDIA DGX Display
Loaded backend 1: OpenCL
  (no devices found)
Loaded backend 2: OpenMP
  Found device: hipSYCL OpenMP host device

=================Device information===================
***************** Devices for backend CUDA *****************
Device 0:
 General device information:
  Name: NVIDIA A100-SXM4-40GB
  Backend: CUDA
  Vendor: NVIDIA
  Arch: sm_80
  Driver version: 12000
  Is CPU: 0
  Is GPU: 1
 Default executor information:
  Is in-order queue: 0
  Is out-of-order queue: 1
  Is task graph: 0
 Device support queries:
  images: 0
  error_correction: 0
  host_unified_memory: 0
  little_endian: 1
  global_mem_cache: 1
  global_mem_cache_read_only: 0
  global_mem_cache_read_write: 1
  emulated_local_memory: 0
  sub_group_independent_forward_progress: 1
  usm_device_allocations: 1
  usm_host_allocations: 1
  usm_atomic_host_allocations: 0
  usm_shared_allocations: 1
  usm_atomic_shared_allocations: 0
  usm_system_allocations: 0
  execution_timestamps: 1
  sscp_kernels: 1
 Device properties:
  max_compute_units: 108
  max_global_size0: 2199023254528
  max_global_size1: 67107840
  max_global_size2: 4194240
  max_group_size: 1024
  max_num_sub_groups: 32
  preferred_vector_width_char: 4
  preferred_vector_width_double: 1
  preferred_vector_width_float: 1
  preferred_vector_width_half: 2
  preferred_vector_width_int: 1
  preferred_vector_width_long: 1
  preferred_vector_width_short: 2
  native_vector_width_char: 4
  native_vector_width_double: 1
  native_vector_width_float: 1
  native_vector_width_half: 2
  native_vector_width_int: 1
  native_vector_width_long: 1
  native_vector_width_short: 2
  max_clock_speed: 1410
  max_malloc_size: 42296475648
  address_bits: 64
  max_read_image_args: 0
  max_write_image_args: 0
  image2d_max_width: 0
  image2d_max_height: 0
  image3d_max_width: 0
  image3d_max_height: 0
  image3d_max_depth: 0
  image_max_buffer_size: 0
  image_max_array_size: 0
  max_samplers: 0
  max_parameter_size: 18446744073709551615
  mem_base_addr_align: 8
  global_mem_cache_line_size: 128
  global_mem_cache_size: 41943040
  global_mem_size: 42296475648
  max_constant_buffer_size: 65536
  max_constant_args: 18446744073709551615
  local_mem_size: 49152
  printf_buffer_size: 18446744073709551615
  partition_max_sub_devices: 0
  vendor_id: 4318
  sub_group_sizes: 32 


Device 1:
 General device information:
  Name: NVIDIA A100-SXM4-40GB
  Backend: CUDA
  Vendor: NVIDIA
  Arch: sm_80
  Driver version: 12000
  Is CPU: 0
  Is GPU: 1
 Default executor information:
  Is in-order queue: 0
  Is out-of-order queue: 1
  Is task graph: 0
 Device support queries:
  images: 0
  error_correction: 0
  host_unified_memory: 0
  little_endian: 1
  global_mem_cache: 1
  global_mem_cache_read_only: 0
  global_mem_cache_read_write: 1
  emulated_local_memory: 0
  sub_group_independent_forward_progress: 1
  usm_device_allocations: 1
  usm_host_allocations: 1
  usm_atomic_host_allocations: 0
  usm_shared_allocations: 1
  usm_atomic_shared_allocations: 0
  usm_system_allocations: 0
  execution_timestamps: 1
  sscp_kernels: 1
 Device properties:
  max_compute_units: 108
  max_global_size0: 2199023254528
  max_global_size1: 67107840
  max_global_size2: 4194240
  max_group_size: 1024
  max_num_sub_groups: 32
  preferred_vector_width_char: 4
  preferred_vector_width_double: 1
  preferred_vector_width_float: 1
  preferred_vector_width_half: 2
  preferred_vector_width_int: 1
  preferred_vector_width_long: 1
  preferred_vector_width_short: 2
  native_vector_width_char: 4
  native_vector_width_double: 1
  native_vector_width_float: 1
  native_vector_width_half: 2
  native_vector_width_int: 1
  native_vector_width_long: 1
  native_vector_width_short: 2
  max_clock_speed: 1410
  max_malloc_size: 42296475648
  address_bits: 64
  max_read_image_args: 0
  max_write_image_args: 0
  image2d_max_width: 0
  image2d_max_height: 0
  image3d_max_width: 0
  image3d_max_height: 0
  image3d_max_depth: 0
  image_max_buffer_size: 0
  image_max_array_size: 0
  max_samplers: 0
  max_parameter_size: 18446744073709551615
  mem_base_addr_align: 8
  global_mem_cache_line_size: 128
  global_mem_cache_size: 41943040
  global_mem_size: 42296475648
  max_constant_buffer_size: 65536
  max_constant_args: 18446744073709551615
  local_mem_size: 49152
  printf_buffer_size: 18446744073709551615
  partition_max_sub_devices: 0
  vendor_id: 4318
  sub_group_sizes: 32 


Device 2:
 General device information:
  Name: NVIDIA A100-SXM4-40GB
  Backend: CUDA
  Vendor: NVIDIA
  Arch: sm_80
  Driver version: 12000
  Is CPU: 0
  Is GPU: 1
 Default executor information:
  Is in-order queue: 0
  Is out-of-order queue: 1
  Is task graph: 0
 Device support queries:
  images: 0
  error_correction: 0
  host_unified_memory: 0
  little_endian: 1
  global_mem_cache: 1
  global_mem_cache_read_only: 0
  global_mem_cache_read_write: 1
  emulated_local_memory: 0
  sub_group_independent_forward_progress: 1
  usm_device_allocations: 1
  usm_host_allocations: 1
  usm_atomic_host_allocations: 0
  usm_shared_allocations: 1
  usm_atomic_shared_allocations: 0
  usm_system_allocations: 0
  execution_timestamps: 1
  sscp_kernels: 1
 Device properties:
  max_compute_units: 108
  max_global_size0: 2199023254528
  max_global_size1: 67107840
  max_global_size2: 4194240
  max_group_size: 1024
  max_num_sub_groups: 32
  preferred_vector_width_char: 4
  preferred_vector_width_double: 1
  preferred_vector_width_float: 1
  preferred_vector_width_half: 2
  preferred_vector_width_int: 1
  preferred_vector_width_long: 1
  preferred_vector_width_short: 2
  native_vector_width_char: 4
  native_vector_width_double: 1
  native_vector_width_float: 1
  native_vector_width_half: 2
  native_vector_width_int: 1
  native_vector_width_long: 1
  native_vector_width_short: 2
  max_clock_speed: 1410
  max_malloc_size: 42296475648
  address_bits: 64
  max_read_image_args: 0
  max_write_image_args: 0
  image2d_max_width: 0
  image2d_max_height: 0
  image3d_max_width: 0
  image3d_max_height: 0
  image3d_max_depth: 0
  image_max_buffer_size: 0
  image_max_array_size: 0
  max_samplers: 0
  max_parameter_size: 18446744073709551615
  mem_base_addr_align: 8
  global_mem_cache_line_size: 128
  global_mem_cache_size: 41943040
  global_mem_size: 42296475648
  max_constant_buffer_size: 65536
  max_constant_args: 18446744073709551615
  local_mem_size: 49152
  printf_buffer_size: 18446744073709551615
  partition_max_sub_devices: 0
  vendor_id: 4318
  sub_group_sizes: 32 


Device 3:
 General device information:
  Name: NVIDIA A100-SXM4-40GB
  Backend: CUDA
  Vendor: NVIDIA
  Arch: sm_80
  Driver version: 12000
  Is CPU: 0
  Is GPU: 1
 Default executor information:
  Is in-order queue: 0
  Is out-of-order queue: 1
  Is task graph: 0
 Device support queries:
  images: 0
  error_correction: 0
  host_unified_memory: 0
  little_endian: 1
  global_mem_cache: 1
  global_mem_cache_read_only: 0
  global_mem_cache_read_write: 1
  emulated_local_memory: 0
  sub_group_independent_forward_progress: 1
  usm_device_allocations: 1
  usm_host_allocations: 1
  usm_atomic_host_allocations: 0
  usm_shared_allocations: 1
  usm_atomic_shared_allocations: 0
  usm_system_allocations: 0
  execution_timestamps: 1
  sscp_kernels: 1
 Device properties:
  max_compute_units: 108
  max_global_size0: 2199023254528
  max_global_size1: 67107840
  max_global_size2: 4194240
  max_group_size: 1024
  max_num_sub_groups: 32
  preferred_vector_width_char: 4
  preferred_vector_width_double: 1
  preferred_vector_width_float: 1
  preferred_vector_width_half: 2
  preferred_vector_width_int: 1
  preferred_vector_width_long: 1
  preferred_vector_width_short: 2
  native_vector_width_char: 4
  native_vector_width_double: 1
  native_vector_width_float: 1
  native_vector_width_half: 2
  native_vector_width_int: 1
  native_vector_width_long: 1
  native_vector_width_short: 2
  max_clock_speed: 1410
  max_malloc_size: 42296475648
  address_bits: 64
  max_read_image_args: 0
  max_write_image_args: 0
  image2d_max_width: 0
  image2d_max_height: 0
  image3d_max_width: 0
  image3d_max_height: 0
  image3d_max_depth: 0
  image_max_buffer_size: 0
  image_max_array_size: 0
  max_samplers: 0
  max_parameter_size: 18446744073709551615
  mem_base_addr_align: 8
  global_mem_cache_line_size: 128
  global_mem_cache_size: 41943040
  global_mem_size: 42296475648
  max_constant_buffer_size: 65536
  max_constant_args: 18446744073709551615
  local_mem_size: 49152
  printf_buffer_size: 18446744073709551615
  partition_max_sub_devices: 0
  vendor_id: 4318
  sub_group_sizes: 32 


Device 4:
 General device information:
  Name: NVIDIA DGX Display
  Backend: CUDA
  Vendor: NVIDIA
  Arch: sm_75
  Driver version: 12000
  Is CPU: 0
  Is GPU: 1
 Default executor information:
  Is in-order queue: 0
  Is out-of-order queue: 1
  Is task graph: 0
 Device support queries:
  images: 0
  error_correction: 0
  host_unified_memory: 0
  little_endian: 1
  global_mem_cache: 1
  global_mem_cache_read_only: 0
  global_mem_cache_read_write: 1
  emulated_local_memory: 0
  sub_group_independent_forward_progress: 1
  usm_device_allocations: 1
  usm_host_allocations: 1
  usm_atomic_host_allocations: 0
  usm_shared_allocations: 1
  usm_atomic_shared_allocations: 0
  usm_system_allocations: 0
  execution_timestamps: 1
  sscp_kernels: 1
 Device properties:
  max_compute_units: 14
  max_global_size0: 2199023254528
  max_global_size1: 67107840
  max_global_size2: 4194240
  max_group_size: 1024
  max_num_sub_groups: 32
  preferred_vector_width_char: 4
  preferred_vector_width_double: 1
  preferred_vector_width_float: 1
  preferred_vector_width_half: 2
  preferred_vector_width_int: 1
  preferred_vector_width_long: 1
  preferred_vector_width_short: 2
  native_vector_width_char: 4
  native_vector_width_double: 1
  native_vector_width_float: 1
  native_vector_width_half: 2
  native_vector_width_int: 1
  native_vector_width_long: 1
  native_vector_width_short: 2
  max_clock_speed: 1395
  max_malloc_size: 4093509632
  address_bits: 64
  max_read_image_args: 0
  max_write_image_args: 0
  image2d_max_width: 0
  image2d_max_height: 0
  image3d_max_width: 0
  image3d_max_height: 0
  image3d_max_depth: 0
  image_max_buffer_size: 0
  image_max_array_size: 0
  max_samplers: 0
  max_parameter_size: 18446744073709551615
  mem_base_addr_align: 8
  global_mem_cache_line_size: 128
  global_mem_cache_size: 1048576
  global_mem_size: 4093509632
  max_constant_buffer_size: 65536
  max_constant_args: 18446744073709551615
  local_mem_size: 49152
  printf_buffer_size: 18446744073709551615
  partition_max_sub_devices: 0
  vendor_id: 4318
  sub_group_sizes: 32 


***************** Devices for backend OpenCL *****************
  (no devices)


***************** Devices for backend OpenMP *****************
Device 0:
 General device information:
  Name: hipSYCL OpenMP host device
  Backend: OpenMP
  Vendor: the hipSYCL project
  Arch: <native-cpu>
  Driver version: 1.2
  Is CPU: 1
  Is GPU: 0
 Default executor information:
  Is in-order queue: 0
  Is out-of-order queue: 1
  Is task graph: 0
 Device support queries:
  images: 0
  error_correction: 0
  host_unified_memory: 1
  little_endian: 1
  global_mem_cache: 1
  global_mem_cache_read_only: 0
  global_mem_cache_read_write: 1
  emulated_local_memory: 1
  sub_group_independent_forward_progress: 0
  usm_device_allocations: 1
  usm_host_allocations: 1
  usm_atomic_host_allocations: 1
  usm_shared_allocations: 1
  usm_atomic_shared_allocations: 1
  usm_system_allocations: 1
  execution_timestamps: 1
  sscp_kernels: 0
 Device properties:
  max_compute_units: 128
  max_global_size0: 18446744073709551615
  max_global_size1: 18446744073709551615
  max_global_size2: 18446744073709551615
  max_group_size: 1024
  max_num_sub_groups: 18446744073709551615
  preferred_vector_width_char: 4
  preferred_vector_width_double: 1
  preferred_vector_width_float: 1
  preferred_vector_width_half: 2
  preferred_vector_width_int: 1
  preferred_vector_width_long: 1
  preferred_vector_width_short: 2
  native_vector_width_char: 4
  native_vector_width_double: 1
  native_vector_width_float: 1
  native_vector_width_half: 2
  native_vector_width_int: 1
  native_vector_width_long: 1
  native_vector_width_short: 2
  max_clock_speed: 0
  max_malloc_size: 18446744073709551615
  address_bits: 64
  max_read_image_args: 0
  max_write_image_args: 0
  image2d_max_width: 0
  image2d_max_height: 0
  image3d_max_width: 0
  image3d_max_height: 0
  image3d_max_depth: 0
  image_max_buffer_size: 0
  image_max_array_size: 0
  max_samplers: 0
  max_parameter_size: 18446744073709551615
  mem_base_addr_align: 8
  global_mem_cache_line_size: 64
  global_mem_cache_size: 1
  global_mem_size: 18446744073709551615
  max_constant_buffer_size: 18446744073709551615
  max_constant_args: 18446744073709551615
  local_mem_size: 18446744073709551615
  printf_buffer_size: 18446744073709551615
  partition_max_sub_devices: 0
  vendor_id: 18446744073709551615
  sub_group_sizes: 1 


```

**Comment by nilsfriess** [comment]
Thanks for reporting. Could you share a small reproducer?

**Comment by tdavidcl** [comment]
Yes, i will try to make one, it shouldn't be too hard since it crash at startup

**Comment by illuhad** [comment]
I've tried on a system with 4x A100. My test apps all work fine so far. We're waiting for that reproducer :)
