### ISSUE TITLE
Support for AMD MI100?

### ISSUE THREAD

**Issue by cgleggett** [AdaptiveCpp/AdaptiveCpp#563]
Does hipSYCL support the AMD MI100? I tried targeting the architecture **hip:gfx908**, but the process/kernel hangs at runtime.

**Comment by illuhad** [comment]
Yes, MI100 is supported - I have validated hipSYCL on the MI100 GPUs in the AMD Accelerator Cloud. However, ROCm still seems to be somewhat buggy on MI100. I tried with ROCm 4.1. You may have a harder time on earlier ROCm stacks.

**Comment by cgleggett** [comment]
I'm using hipSYCL-*-0.9.1-20210516, and ROCM 4.2. The program works fine on a Vega56, but hangs at the following on the MI100:
```
#0  0x00007ffff5cd1d2f in do_futex_wait () from /lib64/libpthread.so.0
#1  0x00007ffff5cd1e07 in __new_sem_wait_slow () from /lib64/libpthread.so.0
#2  0x00007ffff5cd1ea5 in sem_timedwait () from /lib64/libpthread.so.0
#3  0x00007ffff6f3495b in amd::Semaphore::timedWait (this=<optimized out>, millis=10)
    at /tmp/hipsyclbot/spack-stage/spack-stage-hip-rocclr-4.0.0-efoizumerlyg2m3mm2smik2vu7yaxoqr/spack-src/thread/semaphore.cpp:130
#4  0x00007ffff6f3460d in amd::Monitor::wait (this=0x715dd0)
    at /tmp/hipsyclbot/spack-stage/spack-stage-hip-rocclr-4.0.0-efoizumerlyg2m3mm2smik2vu7yaxoqr/spack-src/thread/monitor.cpp:254
#5  0x00007ffff6f5501d in amd::HostQueue::HostQueue (this=0x715da0, context=..., device=..., 
    properties=<optimized out>, queueRTCUs=<optimized out>, priority=<optimized out>, cuMask=...)
    at /tmp/hipsyclbot/spack-stage/spack-stage-hip-rocclr-4.0.0-efoizumerlyg2m3mm2smik2vu7yaxoqr/spack-src/platform/commandqueue.cpp:44
#6  0x00007ffff6ee7d81 in hip::Stream::Create (this=this@entry=0x713d30)
    at /tmp/hipsyclbot/spack-stage/spack-stage-hip-4.0.0-mut2hlgbaomr5zwzpl3lc2slnntkveg2/spack-src/rocclr/hip_stream.cpp:75
#7  0x00007ffff6ee8b0a in ihipStreamCreate (stream=0x715a68, flags=1, priority=hip::Stream::Normal, cuMask=...)
    at /tmp/hipsyclbot/spack-stage/spack-stage-hip-4.0.0-mut2hlgbaomr5zwzpl3lc2slnntkveg2/spack-src/rocclr/hip_stream.cpp:205
#8  hipStreamCreateWithFlags (stream=0x715a68, flags=1)
    at /tmp/hipsyclbot/spack-stage/spack-stage-hip-4.0.0-mut2hlgbaomr5zwzpl3lc2slnntkveg2/spack-src/rocclr/hip_stream.cpp:222
#9  0x00007fffec492eb1 in hipsycl::rt::hip_queue::hip_queue(hipsycl::rt::device_id) ()
   from /opt/hipSYCL/bin/../lib/hipSYCL/librt-backend-hip.so
#10 0x00007fffec49f9ad in std::_Function_handler<std::unique_ptr<hipsycl::rt::inorder_queue, std::default_delete<hipsycl::rt::inorder_queue> > (hipsycl::rt::device_id), hipsycl::rt::hip_backend::hip_backend()::$_0>::_M_invoke(std::_Any_data const&, hipsycl::rt::device_id&&) () from /opt/hipSYCL/bin/../lib/hipSYCL/librt-backend-hip.so
#11 0x00007ffff7b64c08 in hipsycl::rt::multi_queue_executor::multi_queue_executor(hipsycl::rt::backend const&, std::function<std::unique_ptr<hipsycl::rt::inorder_queue, std::default_delete<hipsycl::rt::inorder_queue> > (hipsycl::rt::device_id)>) () from /opt/hipSYCL/bin/../lib/libhipSYCL-rt.so
#12 0x00007fffec49e8a9 in hipsycl::rt::hip_backend::hip_backend() ()
   from /opt/hipSYCL/bin/../lib/hipSYCL/librt-backend-hip.so
--Type <RET> for more, q to quit, c to continue without paging--
#13 0x00007fffec49e819 in hipsycl_backend_plugin_create () from /opt/hipSYCL/bin/../lib/hipSYCL/librt-backend-hip.so
#14 0x00007ffff7b5ebae in hipsycl::rt::backend_loader::create(unsigned long) const ()
   from /opt/hipSYCL/bin/../lib/libhipSYCL-rt.so
#15 0x00007ffff7b5b0e3 in hipsycl::rt::backend_manager::backend_manager() ()
   from /opt/hipSYCL/bin/../lib/libhipSYCL-rt.so
#16 0x00007ffff7b592ea in hipsycl::rt::runtime::runtime() () from /opt/hipSYCL/bin/../lib/libhipSYCL-rt.so
#17 0x00007ffff7b56a5b in hipsycl::rt::(anonymous namespace)::rt_manager::get() ()
   from /opt/hipSYCL/bin/../lib/libhipSYCL-rt.so
#18 0x00007ffff7b56ae6 in hipsycl::rt::application::backends() () from /opt/hipSYCL/bin/../lib/libhipSYCL-rt.so
#19 0x00007ffff7ee051f in hipsycl::sycl::device::get_devices (deviceType=hipsycl::sycl::info::device_type::all)
    at /opt/hipSYCL/bin/../include/CL/../hipSYCL/sycl/device.hpp:223
#20 hipsycl::sycl::detail::select_device<Acts::Sycl::DeviceSelector> (s=...)
    at /opt/hipSYCL/bin/../include/CL/../hipSYCL/sycl/device_selector.hpp:103
```
FWIW, the host has 2 MI100s in it.

Hmm, looks like there's an issue iterating over the 2 devices - it always hangs at the second. If I reduce visibility to just the first with `HIP_VISIBLE_DEVICES=0`, it's ok. Not sure if this is a hardware or driver issue - I can reproduce it with plain hip.
