### ISSUE TITLE
Hang on device reduction kernel with 1 work item per group.

### ISSUE THREAD

**Issue by frobnitzem** [AdaptiveCpp/AdaptiveCpp#857]
**Bug summary**

A generic reduction kernel hangs on the device when I supply an nd_range with only 1 work item per group.
I only observe the hang when running on the device, and only if using a reduction.

Thread backtrace shows it's stuck in the buffer destructor:
```
#0  0x000015554ebb370c in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
#1  0x000015554fef9420 in __gthread_cond_wait (__mutex=<optimized out>, 
    __cond=<optimized out>)
    at /ptmp/peint/build-cray-gcc-20210813.230140.804215673/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/include/x86_64-suse-linux/bits/gthr-default.h:865
#2  std::__condvar::wait (__m=..., this=<optimized out>)
    at /ptmp/peint/build-cray-gcc-20210813.230140.804215673/cray-gcc/BUILD/snos_objdir/x86_64-suse-linux/libstdc++-v3/include/bits/std_mutex.h:155
#3  std::condition_variable::wait (this=<optimized out>, __lock=...)
    at ../../../../../cpe-gcc-11.2.0-202108140355.9bf1fd589a5c1/libstdc++-v3/src/c++11/condition_variable.cc:41
#4  0x0000155555542b3b in hipsycl::rt::worker_thread::wait() ()
   from /ccs/proj/stf006/rogersdd/crusher/lib/libhipSYCL-rt.so
#5  0x000000000028113b in hipsycl::sycl::detail::buffer_impl::~buffer_impl() ()
#6  0x00000000002808e9 in void __gnu_cxx::new_allocator<hipsycl::sycl::detail::buffer_impl>::destroy<hipsycl::sycl::detail::buffer_impl>(hipsycl::sycl::detail::buffer_impl*) ()
#7  0x000000000028088d in void std::allocator_traits<std::allocator<hipsycl::sycl::detail::buffer_impl> >::destroy<hipsycl::sycl::detail::buffer_impl>(std::allocator<hipsycl::sycl::detail::buffer_impl>&, hipsycl::sycl::detail::buffer_impl*) ()
#8  0x00000000002805c6 in std::_Sp_counted_ptr_inplace<hipsycl::sycl::detail::buffer_impl, std::allocator<hipsycl::sycl::detail::buffer_impl>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() ()
#9  0x00000000002669f3 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#10 0x00000000002669aa in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() ()
#11 0x0000000000287bb9 in std::__shared_ptr<hipsycl::sycl::detail::buffer_impl, 
...
```

**To Reproduce**
Compile and run the following code:
```
#include <stdio.h>
#include <stdlib.h>
#include <CL/sycl.hpp>

namespace sycl = cl::sycl;

int main(int argc, char *argv[]) {
    int N = 0;
    int groups = 4;
    int width = 1;
    if(argc > 1) {
        groups = atoi(argv[1]);
    }
    if(argc > 2) {
        width = atoi(argv[2]);
    }

    sycl::queue q;

    if(1) {
      sycl::buffer<int,1> ret(&N, 1);
      q.submit([&](sycl::handler &cgh) {
        sycl::nd_range<1> rng(groups*width, width);
        sycl::accessor<int, 1> d_ret(ret, cgh);//, sycl::read_write);
        const size_t count = 1 << 6;

        cgh.parallel_for(rng,
                sycl::reduction(d_ret, sycl::plus<int>()),
                [count=count](sycl::nd_item<1> it, auto &ans) {
            sycl::group<1> g = it.get_group();
            printf("count %d id %d range %d\n",
                    count, g.get_group_linear_id(),
                    g.get_group_linear_range());
            ans += 1;
        });
      });
    }

    printf("Launched %d workers.\n", N);
    return 0;
}
```

Passing a value >1 for the width works, but with `width=1`, it deadlocks.

**Expected behavior**
The code should run successfully for all device-supported values of groups and width.

**Describe your setup**
* I installed commit 2d937998228826f183a670d927749a4e6cb93a11 from July 13 and am running on AMD gfx90a.

* Describe the dependencies that hipSYCL sits on top of in your setup: 
   * host compiler cce/14.0.0
   * boost 1.79.0
   * ROCm version 5.1.0
   * llvm includes /opt/rocm-5.1.0/llvm/lib/clang/14.0.0/include

* How you have compiled your application: `syclcc --hipsycl-gpu-arch=gfx90a -o err err.cpp`

**Additional context**

Error discovered while running device-accelerated tests on a hash table implementation <https://github.com/ORNL/SYCLhash>.

**Comment by illuhad** [comment]
Thank you, I think I can reproduce.

It hangs in the buffer destructor because the destructor waits for the kernels to complete, which never happens.

The reason is because there seems to be a bug in the way we determine the number of reduction kernels. The way it works is that the user kernel performs a work group reduction, and then we spawn one (or multiple) pure reduction kernels afterwards that then aggregate the work group results into one global result.
It seems that currently those kernels just reuse the group size of the user kernel. If that group size is one however, no additional group reduction can take place, and the reduction never results in a single value. So it should be easy to fix by defaulting to a group size > 1 for the reduction kernels in case the user group size is 1.

Because of this, it actually works if the number of work groups is one, but if you have more than one work group and a local size of 1, it hangs.
